Kp todo
kaizadp/nmrrr pull request #35
Opened 2022-08-27 18:00 UTC by kaizadp

- fixed KP_TODO:
  - function descriptions
  - Hertkorn2013 data description/rda
  - @bpbond Does this look ok?
- rename `gg_spectra` -> `nor_plot_spectra`
- updated function descriptions (.Rd files)
- added authors

Closes #16

2022-08-29 08:13 UTC, bpbond requested changes
Looks good! A few minor suggestions below.

2022-08-29 08:13 UTC, bpbond commented on R/1-functions_graphs.R
>  #' @export
Provide an `@examples`?

2022-08-29 08:13 UTC, bpbond commented on R/1-functions_processing.R
> +#' @param method software used for initial processing of NMR spectra (before using this package). Available options include "mnova" and "topspin".
"Software"

2022-08-29 08:13 UTC, bpbond commented on R/data.R
> +#' (6) amide, from proteins (7.8–8.4 ppm).
Beautiful—thank you!

2022-08-29 21:39 UTC, kaizadp commented
Thanks, changes made!

fbd85503a1c312d083f5a3f4ed88c2acbf8b0c9a 
237a05761c66273cb219503b6b950a67e99e3f35

The `nmr_plot_spectra` example is a little weird for meb_burn data, because the intensities are very high and have not been normalized. Will update the example later, when Morgan gives me simpler, normalized data.

2022-09-02 19:56 UTC, merged

2022-09-02 19:57 UTC, bpbond commented
So as a general rule of thumb: please don't merge PRs with failing tests. I will look at this later.

2022-09-02 19:59 UTC, kaizadp commented
Good point! I think I know what’s causing the tests to fail, so I’m working on it right now.
Next time, I’ll fix before merging. 
Thanks!

2022-09-02 20:56 UTC, bpbond commented
Thanks! Sorry if that sounded grumpy :)

2022-09-02 21:10 UTC, kaizadp commented
No worries, I was impatient to merge branches.

PS: there's still an error. The previous error was because I changed the function name (`nmr_plot_spectra`) but didn't update the tests and documentation. I did so, and now I get this error:
(not urgent, when you get a chance later)

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/50244730/188235501-3ce8a41f-e52d-4f3d-a9d0-fdc57ba71f40.png">